name: .NET Core

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: Deployment
      
      run: |
        
        sudo yum install -y dos2unix
        dos2unix /home/ec2-user/actions-runner/_work/communication-qa/communication_deploy.sh
        sudo chmod a+x /home/ec2-user/actions-runner/_work/communication-qa/communication_deploy.sh
        cd /home/ec2-user/actions-runner/_work/communication-qa/
        sudo ./communication_deploy.sh
